version: '3'  # Downgrade from 3.8 for better compatibility

services:
  web:
    build: .
    expose:
      - "8000"
    depends_on:
      - db
      - mosquitto
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nest_db
      - SECRET_KEY=${SECRET_KEY}
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=1107
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_db
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"  # Changed to avoid port conflicts
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: always

  nodered:
    image: nodered/node-red:latest
    ports:
       - "1880:1880"  # Node-RED web interface
    volumes:
       - ./node-red-data:/data  # Persist flows and settings
    depends_on:
       - mosquitto  # Ensure Mosquitto starts first
    restart: always
volumes:
  postgres_data: